# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(408, 719)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 421, 721))
        self.groupBox.setStyleSheet("background-color: rgb(188, 218, 255);")
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 200, 311, 261))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelUsername = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelUsername.setFont(font)
        self.labelUsername.setStyleSheet("color: rgb(86, 98, 122);")
        self.labelUsername.setObjectName("labelUsername")
        self.verticalLayout.addWidget(self.labelUsername)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        self.username = QtWidgets.QLineEdit(self.layoutWidget)
        self.username.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.username.setObjectName("username")
        self.verticalLayout_5.addWidget(self.username)
        self.labelPassword = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelPassword.setFont(font)
        self.labelPassword.setStyleSheet("color: rgb(86, 98, 122);")
        self.labelPassword.setObjectName("labelPassword")
        self.verticalLayout_5.addWidget(self.labelPassword)
        self.password = QtWidgets.QLineEdit(self.layoutWidget)
        self.password.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.password.setObjectName("password")
        self.verticalLayout_5.addWidget(self.password)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.loginbutton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.loginbutton.setFont(font)
        self.loginbutton.setStyleSheet("color: rgb(86, 98, 122);\n"
"background-color: rgb(227, 180, 180);")
        self.loginbutton.setObjectName("loginbutton")
        self.verticalLayout_2.addWidget(self.loginbutton)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.BOOKALL_2 = QtWidgets.QLabel(self.groupBox)
        self.BOOKALL_2.setGeometry(QtCore.QRect(150, 70, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Forte")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.BOOKALL_2.setFont(font)
        self.BOOKALL_2.setStyleSheet("background-color: rgb(188, 218, 255);\n"
"color: rgb(27, 36, 156);\n"
"\n"
"")
        self.BOOKALL_2.setObjectName("BOOKALL_2")
        self.frame = QtWidgets.QFrame(self.groupBox)
        self.frame.setGeometry(QtCore.QRect(40, 190, 331, 281))
        self.frame.setStyleSheet("background-color: rgb(205, 255, 228);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame.raise_()
        self.layoutWidget.raise_()
        self.BOOKALL_2.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "Sign in"))
        self.labelUsername.setText(_translate("Dialog", "Username"))
        self.labelPassword.setText(_translate("Dialog", "Password"))
        self.loginbutton.setText(_translate("Dialog", "Sign In"))
        self.BOOKALL_2.setText(_translate("Dialog", "BOOKALL"))
